excluded:
  - Package.swift
disabled_rules:
  - todo
opt_in_rules:
  - file_name_no_space
  - force_unwrapping
  - function_default_parameter_at_end
  - implicitly_unwrapped_optional
  - lower_acl_than_parent
  - modifier_order
  - overridden_super_call
  - unowned_variable_capture
  - unused_import
line_length: 100
identifier_name:
  excluded:
    - id
    - to
